### ISSUE TITLE
Width of entity unwieldy when collapsed if arg vec long

### ISSUE THREAD

**Issue by sogaiu** [jpmonettas/clograms#1]
Very much appreciate the ability to collapse the code body :+1: 

When I collapse a function that has a long argument vector, the width gets unwieldy:

![entity-width](https://user-images.githubusercontent.com/33044872/69890998-99f29980-133c-11ea-84b5-53bd41dd6c4c.png)

Is this something I can tweak without modifying my source?

**Comment by jpmonettas** [comment]
Thanks for reporting that @sogaiu, https://github.com/jpmonettas/clograms/commit/f04b4a98935809627cd2be91f6caadb43254498a should fix it.
