### ISSUE TITLE
Blank page after connecting to localhost:3000

### ISSUE THREAD

**Issue by sogaiu** [jpmonettas/clograms#3]
After invoking:
```
clj -Sdeps '{:deps {clograms {:mvn/version "RELEASE"}}}' -m clograms.server . clj
```
in a JVM Clojure project directory and waiting for the output:
```
...
indexing  clj-kondo.impl.utils
indexing  clojure.template
About to transact 245090 facts
Watching  (/home/user/Desktop/src/alc.index-defs/src)
Indexing done, open http://localhost:3000
```
Visited localhost:3000 in Firefox, Brave, and Chromium, but am met with a blank page.

Opening a browser's devtools, I see the following in the console:
```
WebSocket connection to 'ws://localhost:3449/figwheel-ws/dev' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
figwheel$client$socket$open @ socket.cljs?rel=1502542805393:64
```
FWIW, there didn't appear to be anything listening on port 3449 according to lsof and netstat -na.

May be I have missed a step or done something wrong?

**Comment by sogaiu** [comment]
FWIW, when I explicitly specify 0.1.4, I don't get a blank page, but rather the expected "Loading" sequence.

**Comment by jpmonettas** [comment]
Yeah this should be fixed on master on 0.1.7, not sure how RELEASE works with clj cache system so maybe explicitly try 0.1.7

The problem should have been fixed in 62e75715f2c999abdb342aef7b2542eacaa0717e. It was caused by another dependency adding a index.html file in resources so some times it was serving a different file, something that was compiled with fighwheel. 

I will go deeper in to that but in the meantime I just renamed main html file into clograms.html

**Comment by jpmonettas** [comment]
If not sure what version RELEASE is pulling you can try : 
`clj -Sdeps '{:deps {clograms {:mvn/version "RELEASE"}}}' -Spath | grep --color clograms`

**Comment by sogaiu** [comment]
Nice trick with the grep --color :)

I see 0.1.5 -- and when I use that explicitly it also doesn't work.

Explicitly using 0.1.7 does work :+1: 

On a side note, the width issue seems appropriately addressed.  TYVM!

**Comment by jpmonettas** [comment]
Glad it worked! Yeah I'm still not sure if using that RELEASE version in the readme is a good idea, it works sometimes, but sometimes it grabs an old version, no idea why.

**Comment by sogaiu** [comment]
May be an explicit version is safer as you hinted.

In any case I'll close this issue :)
