### ISSUE TITLE
Collpasing can lead to visually dangling connection

### ISSUE THREAD

**Issue by sogaiu** [jpmonettas/clograms#6]
clograms 0.1.7

After getting one node on the screen, I clicked on a "link" within the node's code area.  This brought another node on to the screen with a pre-made connection.

Subsequently, clicking on the collapsing triangle of the first node, caused the connection to appear disconnected.

![collapsing-leaves-connection-dangling](https://user-images.githubusercontent.com/33044872/69906324-45ffb780-1405-11ea-9e81-d7312ef01e43.png)

FWIW, moving the first node appears to lead to the connection being visually restored.

Clicking on the second node's collapsing triangle can lead to the same sort of situation as well.

**Comment by jpmonettas** [comment]
Hmm have seen that in the past but couldn't reproduce this time 

![2019-11-30-19-47-31](https://user-images.githubusercontent.com/786299/69906948-6baba300-13aa-11ea-8f99-9e187b68a234.gif)

**Comment by sogaiu** [comment]
It doesn't seem to happen every time here and the connection isn't actually broken, so may be it's not such a big deal, especially because just moving the node a bit seems to fix it.
